//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ButtonLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übernehmen.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achsen-Bearbeitungsmodus wechseln.
        /// </summary>
        internal static string AchsenEditModeWechseln {
            get {
                return ResourceManager.GetString("AchsenEditModeWechseln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achsenupdate durchführen.
        /// </summary>
        internal static string Achsenupdate {
            get {
                return ResourceManager.GetString("Achsenupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Achse erfassen.
        /// </summary>
        internal static string AddAchsen {
            get {
                return ResourceManager.GetString("AddAchsen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Datensatz hinzufügen.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Inspektionsroute erfassen.
        /// </summary>
        internal static string AddNewInspektionsroute {
            get {
                return ResourceManager.GetString("AddNewInspektionsroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Kenngrössen früherer Jahre erfassen.
        /// </summary>
        internal static string AddNewKenngroessenFruehererJahre {
            get {
                return ResourceManager.GetString("AddNewKenngroessenFruehererJahre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue koordinierte Massnahme erfassen.
        /// </summary>
        internal static string AddNewKoordinierteMassnahme {
            get {
                return ResourceManager.GetString("AddNewKoordinierteMassnahme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Massnahme eines Teilsystems erfassen.
        /// </summary>
        internal static string AddNewMassnahmeEinesTeilsystems {
            get {
                return ResourceManager.GetString("AddNewMassnahmeEinesTeilsystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Massnahme anlegen.
        /// </summary>
        internal static string AddNewMassnahmenvorschalg {
            get {
                return ResourceManager.GetString("AddNewMassnahmenvorschalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue realisierte Massnahme erfassen.
        /// </summary>
        internal static string AddNewRealisierteMassnahme {
            get {
                return ResourceManager.GetString("AddNewRealisierteMassnahme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Massnahme anlegen.
        /// </summary>
        internal static string AddNewRealisierteMassnahmenvorschalg {
            get {
                return ResourceManager.GetString("AddNewRealisierteMassnahmenvorschalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Strassenabschnitt erfassen.
        /// </summary>
        internal static string AddNewStrassenabschnitt {
            get {
                return ResourceManager.GetString("AddNewStrassenabschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue mandantenspezifische Wiederbeschaffungs- und Alterungsbeiwerte erfassen.
        /// </summary>
        internal static string AddNewWiederbeschaffungswertUndAlterungsbeiwert {
            get {
                return ResourceManager.GetString("AddNewWiederbeschaffungswertUndAlterungsbeiwert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Zustandsabschnitt erfassen.
        /// </summary>
        internal static string AddNewZustandsabschnitt {
            get {
                return ResourceManager.GetString("AddNewZustandsabschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderen Benutzer(namen) einnehmen.
        /// </summary>
        internal static string AndereBenutzerrollenEinnehmen {
            get {
                return ResourceManager.GetString("AndereBenutzerrollenEinnehmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitsmodus wechseln.
        /// </summary>
        internal static string ArbeitsmodusWechseln {
            get {
                return ResourceManager.GetString("ArbeitsmodusWechseln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zur Übersicht.
        /// </summary>
        internal static string BackToOverview {
            get {
                return ResourceManager.GetString("BackToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender öffnen.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import verwerfen.
        /// </summary>
        internal static string CancelImport {
            get {
                return ResourceManager.GetString("CancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out abbrechen.
        /// </summary>
        internal static string CancellExport {
            get {
                return ResourceManager.GetString("CancellExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string Ch {
            get {
                return ResourceManager.GetString("Ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptieren.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailstufe des Anwendungs-Loggings ändern.
        /// </summary>
        internal static string ChangeLogLevel {
            get {
                return ResourceManager.GetString("ChangeLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ereignis-Log löschen.
        /// </summary>
        internal static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhr.
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schliessen.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import durchführen.
        /// </summary>
        internal static string CommitImport {
            get {
                return ResourceManager.GetString("CommitImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustandsabschnitte kopieren.
        /// </summary>
        internal static string CopyZustandsabschnitt {
            get {
                return ResourceManager.GetString("CopyZustandsabschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herab.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungs-Log herunterladen.
        /// </summary>
        internal static string DownloadApplicationLog {
            get {
                return ResourceManager.GetString("DownloadApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertung herunterladen (Excel).
        /// </summary>
        internal static string DownloadReportExcel {
            get {
                return ResourceManager.GetString("DownloadReportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertung herunterladen (PDF).
        /// </summary>
        internal static string DownloadReportPdf {
            get {
                return ResourceManager.GetString("DownloadReportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        internal static string DownloadShapeExport {
            get {
                return ResourceManager.GetString("DownloadShapeExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string ExpandFilters {
            get {
                return ResourceManager.GetString("ExpandFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Inspektionsroute.
        /// </summary>
        internal static string ExportInspektionsroute {
            get {
                return ResourceManager.GetString("ExportInspektionsroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strassennetz exportieren (.xlsx).
        /// </summary>
        internal static string ExportStrassenabschnitt {
            get {
                return ResourceManager.GetString("ExportStrassenabschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustandsabschnitte exportieren (.xlsx).
        /// </summary>
        internal static string ExportZustandsabschnitte {
            get {
                return ResourceManager.GetString("ExportZustandsabschnitte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustand Fahrbahn erfassen.
        /// </summary>
        internal static string Fahrbahn {
            get {
                return ResourceManager.GetString("Fahrbahn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtern.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswertung ausführen.
        /// </summary>
        internal static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Lokalisierungsdateien herunterladen.
        /// </summary>
        internal static string GetGlobalResources {
            get {
                return ResourceManager.GetString("GetGlobalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe EMSG-Master herunterladen.
        /// </summary>
        internal static string GetMasterHelpSystem {
            get {
                return ResourceManager.GetString("GetMasterHelpSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMSG-Mobile herunterladen.
        /// </summary>
        internal static string GetMobileClient {
            get {
                return ResourceManager.GetString("GetMobileClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe EMSG-Mobile herunterladen.
        /// </summary>
        internal static string GetMobileHelpSystem {
            get {
                return ResourceManager.GetString("GetMobileHelpSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template herunterladen.
        /// </summary>
        internal static string GetStrassennetzImportTemplate {
            get {
                return ResourceManager.GetString("GetStrassennetzImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template herunterladen.
        /// </summary>
        internal static string GetZustandsabschnittImportTemplate {
            get {
                return ResourceManager.GetString("GetZustandsabschnittImportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importieren.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspektionsroute importieren.
        /// </summary>
        internal static string ImportInspektionsroute {
            get {
                return ResourceManager.GetString("ImportInspektionsroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strassennetz importieren (.xlsx).
        /// </summary>
        internal static string ImportStrassennetz {
            get {
                return ResourceManager.GetString("ImportStrassennetz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustandsabschnitte importieren (.xlsx).
        /// </summary>
        internal static string ImportZustandsabschnitt {
            get {
                return ResourceManager.GetString("ImportZustandsabschnitt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string It {
            get {
                return ResourceManager.GetString("It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahresabschluss.
        /// </summary>
        internal static string JahresAbschluss {
            get {
                return ResourceManager.GetString("JahresAbschluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgängig machen.
        /// </summary>
        internal static string LetztenJahresAbschlussRueckgaengingMachen {
            get {
                return ResourceManager.GetString("LetztenJahresAbschlussRueckgaengingMachen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisationsspezifische Kosten festlegen.
        /// </summary>
        internal static string OverrideMassnahmenvorschalg {
            get {
                return ResourceManager.GetString("OverrideMassnahmenvorschalg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau anzeigen.
        /// </summary>
        internal static string PreviewReportPdf {
            get {
                return ResourceManager.GetString("PreviewReportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string ReCalculate {
            get {
                return ResourceManager.GetString("ReCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern und schliessen.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilen.
        /// </summary>
        internal static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusverlauf anzeigen.
        /// </summary>
        internal static string Statusverlauf {
            get {
                return ResourceManager.GetString("Statusverlauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustandsabschnitte anzeigen.
        /// </summary>
        internal static string StrassenabschnittDetail {
            get {
                return ResourceManager.GetString("StrassenabschnittDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string StrassenabschnittenGridFilter {
            get {
                return ResourceManager.GetString("StrassenabschnittenGridFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustand Trottoir erfassen.
        /// </summary>
        internal static string Trottoir {
            get {
                return ResourceManager.GetString("Trottoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelle in separaten Fenster öffnen.
        /// </summary>
        internal static string Undock {
            get {
                return ResourceManager.GetString("Undock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herauf.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
