//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.NotificationLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der von Ihnen bearbeiteten Achse liegen bereits Fachdaten. Sie können die Fachdaten automatisch gemäss Ihrer Veränderung anpassen lassen (adaptieren) oder Sie können die Fachdaten (d.h. Strassen- und Zustandsabschnitte) löschen lassen..
        /// </summary>
        internal static string AchenModificationWarning {
            get {
                return ResourceManager.GetString("AchenModificationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achse bearbeiten bereits aktiviert!.
        /// </summary>
        internal static string AchsenEditEnabled {
            get {
                return ResourceManager.GetString("AchsenEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Beim Wechsel auf &quot;Achsen editieren&quot; verliert der Mandant die Möglichkeit, die Achsen über Inkremente zu aktualisieren. Der Wechsel auf &quot;Achsen editieren&quot; kann nur noch mit der Funktion &quot;Jahresabschluss rückgängig machen&quot; aufgehoben werden..
        /// </summary>
        internal static string AchsenEditModeChangeConfirmation {
            get {
                return ResourceManager.GetString("AchsenEditModeChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung! Bei Umstellung auf Achsen editieren kann das hier direkt nicht mehr rückgängig gemacht werden, sondern nur mit der Jahresabschluss rückgängig machen. .
        /// </summary>
        internal static string AchsenEditModeChangeWarning {
            get {
                return ResourceManager.GetString("AchsenEditModeChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achsen Bearbeitungsmodus wechseln wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string AchsenEditModeChangeWasSuccessfull {
            get {
                return ResourceManager.GetString("AchsenEditModeChangeWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Vorgang kann bis zu 5 Minuten dauern..
        /// </summary>
        internal static string AchsenUpdateConfirmation {
            get {
                return ResourceManager.GetString("AchsenUpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können hier das Achsenupdate durchführen!.
        /// </summary>
        internal static string AchsenUpdateInformation {
            get {
                return ResourceManager.GetString("AchsenUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderen Benutzer(namen) einnehmen wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string AndereBenutzerrollenEinnehmenWasSuccessfull {
            get {
                return ResourceManager.GetString("AndereBenutzerrollenEinnehmenWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achsen-Bearbeitungsmodus wechseln wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string ArbeitsmodusWechselnWasSuccessfull {
            get {
                return ResourceManager.GetString("ArbeitsmodusWechselnWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Belastungskategorie und Belag stimmen nicht überein! Wollen Sie trotzdem Speichern?.
        /// </summary>
        internal static string BelagBelastungskategorieMismatchConfirmation {
            get {
                return ResourceManager.GetString("BelagBelastungskategorieMismatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte beachten Sie, dass bei mindestens einem Strassenabschnitt die Kombination von Belag und Belastungskategorie fachlich fragwürdig ist..
        /// </summary>
        internal static string BelagBelastungskategorieMismatchSplitConfirmation {
            get {
                return ResourceManager.GetString("BelagBelastungskategorieMismatchSplitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben die Belagsart verändert! Sind Sie sicher, dass Sie speichern wollen? Nach dem Speichern wird bei allen Zustandsabschnitten der Zustandsindex zurückgesetzt!.
        /// </summary>
        internal static string BelagChangeConfirmation {
            get {
                return ResourceManager.GetString("BelagChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um Benchmarkauswertungen durchführen zu können, müssen Sie einen Jahresabschluss machen..
        /// </summary>
        internal static string BenchmarkauswertungNoJahresabschlussNotificationText {
            get {
                return ResourceManager.GetString("BenchmarkauswertungNoJahresabschlussNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Die Daten der Benchmarkauswertung ändern sich mit jeder Gemeinde, die einen Jahresabschluss durchführt..
        /// </summary>
        internal static string BenchmarkauswertungNotificationText {
            get {
                return ResourceManager.GetString("BenchmarkauswertungNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Ihre Aktion wird die Erfassung abgebrochen. Sind Sie sicher abbrechen zu wollen?.
        /// </summary>
        internal static string CancelConfirmation {
            get {
                return ResourceManager.GetString("CancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durch Ihre Aktion wird die Zustandserfassung abgebrochen. Sind Sie sicher abbrechen zu wollen?.
        /// </summary>
        internal static string CancelGrobDetailZustandserfassungConfirmation {
            get {
                return ResourceManager.GetString("CancelGrobDetailZustandserfassungConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Import wirklich verwerfen?.
        /// </summary>
        internal static string CancelImportConfirmation {
            get {
                return ResourceManager.GetString("CancelImportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie den Check-Out der Inspektionsroute rückgängig machen möchten?.
        /// </summary>
        internal static string CancellExportConfirmation {
            get {
                return ResourceManager.GetString("CancellExportConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde noch kein Jahresabschluss gemacht. Auswertungen können nur generiert werden, wenn zumindest ein Jahresabschluss gemacht wurde..
        /// </summary>
        internal static string CanNotDoAuswertung {
            get {
                return ResourceManager.GetString("CanNotDoAuswertung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben für das Jahr {0} bereits ein Jahresabschluss gemacht!.
        /// </summary>
        internal static string CanNotJahresAbschluss {
            get {
                return ResourceManager.GetString("CanNotJahresAbschluss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde noch kein Jahresabschluss gemacht. Diese Funktion steht erst zur Verfügung, wenn zumindest ein Jahresabschluss gemacht wurde..
        /// </summary>
        internal static string CanNotUseKenngroessenFruehererJahre {
            get {
                return ResourceManager.GetString("CanNotUseKenngroessenFruehererJahre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie alle Ereignis-Log Einträge löschen wollen?.
        /// </summary>
        internal static string ClearLogConfirmation {
            get {
                return ResourceManager.GetString("ClearLogConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Paket ohne Kartenmaterial kann innerhalb von 30-60 Sekunden bereitgestellt werden.
        ///Möchten Sie das Paket mit Kartenmaterial oder ohne Kartenmaterial herunterladen?.
        /// </summary>
        internal static string ConfirmMapDownload {
            get {
                return ResourceManager.GetString("ConfirmMapDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben die Möglichkeit, die Zustandsabschnitte inklusive der erfassten Schäden und Massnahmenvorschläge vom Vorjahr zu übernehmen..
        /// </summary>
        internal static string CopyZustandsabschnitteInfoText {
            get {
                return ResourceManager.GetString("CopyZustandsabschnitteInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Eintrag wirklich löschen?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte spielen Sie Achsenupdates für Ihren Mandanten ein!.
        /// </summary>
        internal static string DoAchsenUpdateWarning {
            get {
                return ResourceManager.GetString("DoAchsenUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Export muss mindestens eine Inspektionsroute ausgewählt sein!.
        /// </summary>
        internal static string EmptyInspektionsrouteExportWarning {
            get {
                return ResourceManager.GetString("EmptyInspektionsrouteExportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Verarbeiten der Daten ist ein Fehler aufgetreten. Bitte melden Sie dem Applikationsadministrator folgende Fehlerverfolgungsnummer: ({0})..
        /// </summary>
        internal static string ErrorWhileProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorWhileProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Übersetzungsdatei muss eine der heruntergeladenen Dateien (aus der ZIP-Datei) sein..
        /// </summary>
        internal static string GlobaleResourceUploadErrorHelp {
            get {
                return ResourceManager.GetString("GlobaleResourceUploadErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Hochladen der Übersetzungsdatei sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string GlobaleResourceUploadErrorTitle {
            get {
                return ResourceManager.GetString("GlobaleResourceUploadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzungsdatei wurde erfolgreich hochgeladen!.
        /// </summary>
        internal static string GlobaleResourceUploadSuccessful {
            get {
                return ResourceManager.GetString("GlobaleResourceUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Hilfe-Dateien sollen in einen ZIP-Paket sein!.
        /// </summary>
        internal static string HelpSystemUploadErrorHelp {
            get {
                return ResourceManager.GetString("HelpSystemUploadErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Hochladen des Hilfesystems sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string HelpSystemUploadErrorTitle {
            get {
                return ResourceManager.GetString("HelpSystemUploadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfesystem wurde erfolgreich hochgeladen!.
        /// </summary>
        internal static string HelpSystemUploadSuccessful {
            get {
                return ResourceManager.GetString("HelpSystemUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Import sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string ImportInspektionsroutenErrorTitle {
            get {
                return ResourceManager.GetString("ImportInspektionsroutenErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Inspektionsrouten werden gerade importiert. Bitte warten Sie, bis der Vorgang abgeschlossen ist..
        /// </summary>
        internal static string ImportInspektionsroutenProgressText {
            get {
                return ResourceManager.GetString("ImportInspektionsroutenProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Inspektionsrouten wurden erfolgreich importiert..
        /// </summary>
        internal static string ImportInspektionsroutenSuccessful {
            get {
                return ResourceManager.GetString("ImportInspektionsroutenSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Excel-Import für den Strassenabschnitt gibt es folgende Warnungen:.
        /// </summary>
        internal static string ImportStrassenabschnittWarningTitle {
            get {
                return ResourceManager.GetString("ImportStrassenabschnittWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zur Struktur der Excel-Datei und zu den erwarteten Werten finden Sie in der Hilfe..
        /// </summary>
        internal static string ImportStrassennetzErrorHelp {
            get {
                return ResourceManager.GetString("ImportStrassennetzErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Excel-Import für das Strassennetz sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string ImportStrassennetzErrorTitle {
            get {
                return ResourceManager.GetString("ImportStrassennetzErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Strassennetz wird gerade importiert. Bitte warten Sie, bis der Vorgang abgeschlossen ist..
        /// </summary>
        internal static string ImportStrassennetzProgressText {
            get {
                return ResourceManager.GetString("ImportStrassennetzProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Strassennetz wurde erfolgreich importiert..
        /// </summary>
        internal static string ImportStrassennetzSuccessful {
            get {
                return ResourceManager.GetString("ImportStrassennetzSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informationen zur Struktur der Excel-Datei und zu den erwarteten Werten finden Sie in der Hilfe..
        /// </summary>
        internal static string ImportZustandsabschnittErrorHelp {
            get {
                return ResourceManager.GetString("ImportZustandsabschnittErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Excel-Import der Zustandsabschnitte sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string ImportZustandsabschnittErrorTitle {
            get {
                return ResourceManager.GetString("ImportZustandsabschnittErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zustandsabschnitte werden gerade importiert. Bitte warten Sie, bis der Vorgang abgeschlossen ist..
        /// </summary>
        internal static string ImportZustandsabschnittProgressText {
            get {
                return ResourceManager.GetString("ImportZustandsabschnittProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zustandsabschnitte wurden erfolgreich importiert..
        /// </summary>
        internal static string ImportZustandsabschnittSuccessful {
            get {
                return ResourceManager.GetString("ImportZustandsabschnittSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Excel-Import für den Zustandsabschnitt gibt es folgende Warnungen:.
        /// </summary>
        internal static string ImportZustandsabschnittWarningTitle {
            get {
                return ResourceManager.GetString("ImportZustandsabschnittWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Organisationdaten sind nicht komplett! Der Jahresabschluss ist nicht durchführbar! Ergänzen Sie bitte die Organisationsdaten unter dem Menüpunkt Administration / Organisationsdaten bearbeiten!.
        /// </summary>
        internal static string InCompleteMandantenDetails {
            get {
                return ResourceManager.GetString("InCompleteMandantenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Generierung der Exportdatei ist von der Grösse des gewählten Umkreises Ihrer Inspektionsrouten abhängig und zwar wie folgt:
        ///
        ///- Eine Fläche von 1 km&amp;#xb2; dauert 30-50 Sekunden
        ///- Eine Fläche von 10 km&amp;#xb2; dauert 2-3 Minuten
        ///- Eine Fläche von 100 km&amp;#xb2; dauert 2-3 Stunden.
        /// </summary>
        internal static string InspektionsrouteExportTimeWarning {
            get {
                return ResourceManager.GetString("InspektionsrouteExportTimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Eintrag kann nicht gelöscht werden. Die Inspektionsroute ist derzeit exportiert..
        /// </summary>
        internal static string InspektionsrouteLockedDeleteNotification {
            get {
                return ResourceManager.GetString("InspektionsrouteLockedDeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Eintrag kann nicht gespeichert werden. Die Inspektionsroute ist derzeit exportiert..
        /// </summary>
        internal static string InspektionsrouteLockedNotification {
            get {
                return ResourceManager.GetString("InspektionsrouteLockedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Wollen Sie den Jahresabschluss wirklich durchführen?.
        /// </summary>
        internal static string JahresabschlussConfirmation {
            get {
                return ResourceManager.GetString("JahresabschlussConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang kann bis zu {0} Minuten dauern. Während des Vorgangs dürfen keine Daten bearbeitet werden. Bearbeitete Daten können nicht übernommen werden und müssen erneut eingegeben werden. Das Bearbeiten von Daten kann ausserdem zu einem Fehlschlagen des Jahresabschlusses führen. Der Browser kann während des Vorgangs geschlossen werden..
        /// </summary>
        internal static string JahresAbschlussDurationWarning {
            get {
                return ResourceManager.GetString("JahresAbschlussDurationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Nicht für alle Strassenabschnitte wurden Zustandsaufnahmen durchgeführt. Wollen Sie den Jahresabschluss trotzdem durchführen?.
        /// </summary>
        internal static string JahresabschlussMissingZustandsabschnitteConfirmation {
            get {
                return ResourceManager.GetString("JahresabschlussMissingZustandsabschnitteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahresabschluss rückgängig machen wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string JahresAbschlussRueckgaengingMachenWasSuccessfull {
            get {
                return ResourceManager.GetString("JahresAbschlussRueckgaengingMachenWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Jahresabschluss wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string JahresAbschlussWasSuccessfull {
            get {
                return ResourceManager.GetString("JahresAbschlussWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all KenngroessenFruehererJahre.
        /// </summary>
        internal static string KenngroessenFruehererJahreWarning {
            get {
                return ResourceManager.GetString("KenngroessenFruehererJahreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Wollen Sie den Jahresabschluss wirklich rückgängig machen?.
        /// </summary>
        internal static string LetztenJahresAbschlussRueckgaengingMachenWarning {
            get {
                return ResourceManager.GetString("LetztenJahresAbschlussRueckgaengingMachenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Katalogwert wird benutzt und kann daher nicht gelöscht werden!.
        /// </summary>
        internal static string LookupIsUsedCanNotDelete {
            get {
                return ResourceManager.GetString("LookupIsUsedCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Speichern der Organisationsdaten wurde erfolgreich durchgeführt!.
        /// </summary>
        internal static string MandantDetailsModelSpeichernWasSuccessfull {
            get {
                return ResourceManager.GetString("MandantDetailsModelSpeichernWasSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Mandanten-Logo darf nicht grösser sein als 2 MB und darf nur ein Bild sein. (JPEG, BMP, PNG).
        /// </summary>
        internal static string MandantLogoUploadErrorHelp {
            get {
                return ResourceManager.GetString("MandantLogoUploadErrorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Hochladen des Mandanten-Logos sind folgende Fehler aufgetreten:.
        /// </summary>
        internal static string MandantLogoUploadErrorTitle {
            get {
                return ResourceManager.GetString("MandantLogoUploadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandanten-Logo wurde erfolgreich hochgeladen!.
        /// </summary>
        internal static string MandantLogoUploadSuccessful {
            get {
                return ResourceManager.GetString("MandantLogoUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es sind für den ausgewählten Filter keine Daten vorhanden..
        /// </summary>
        internal static string NoDataForTheSelectedFilters {
            get {
                return ResourceManager.GetString("NoDataForTheSelectedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Auswertung kann nicht ausgeführt werden! Es gibt keine Zustandsabschnitte mit detaillierten Formularen für Oberflächenschäden!.
        /// </summary>
        internal static string NoDetallierteSchadenerfassungsformular {
            get {
                return ResourceManager.GetString("NoDetallierteSchadenerfassungsformular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es stehen zu wenige Mandanten für die Benchmarkauswertung zur Verfügung!.
        /// </summary>
        internal static string NotEnoughDataForBechmarking {
            get {
                return ResourceManager.GetString("NotEnoughDataForBechmarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte passen Sie die koordinierten Massnahmen, die Massnahmenvorschläge der Teilsysteme und die Zustände an..
        /// </summary>
        internal static string RealisierteMassnahmeGISSavedWarning {
            get {
                return ResourceManager.GetString("RealisierteMassnahmeGISSavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte passen Sie die Zustände an..
        /// </summary>
        internal static string RealisierteMassnahmeSavedWarning {
            get {
                return ResourceManager.GetString("RealisierteMassnahmeSavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte passen Sie den Wert &quot;Mittlerer Zustand&quot; an..
        /// </summary>
        internal static string RealisierteMassnahmeSummarichSavedWarning {
            get {
                return ResourceManager.GetString("RealisierteMassnahmeSummarichSavedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Auswertung ist im gewählten Jahr nicht möglich, da damals der Jahresabschluss in einem vereinfachten Arbeitsmodus durchgeführt wurde, bei dem die für diese Auswertung notwendigen Daten nicht erfasst wurden..
        /// </summary>
        internal static string ReportModeIncompatiblityNoticitationTest {
            get {
                return ResourceManager.GetString("ReportModeIncompatiblityNoticitationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie speichern wollen? Nach dem Speichern wird der alte Strassenabschnitt (sowie eventuell zum ihm bereits vorhandene Zustandsabschnitte) gelöscht!.
        /// </summary>
        internal static string SplitComfirmation {
            get {
                return ResourceManager.GetString("SplitComfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die neuen Strassenabschnitte sind um {0} Meter länger als der ursprüngliche Strassenabschnitt. Wollen Sie trotzdem speichern?.
        /// </summary>
        internal static string SplitStrassenabschnittLaengeLargerConfirmation {
            get {
                return ResourceManager.GetString("SplitStrassenabschnittLaengeLargerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die neuen Strassenabschnitte sind um {0} Meter kürzer als der ursprüngliche Strassenabschnitt. Wollen Sie trotzdem speichern?.
        /// </summary>
        internal static string SplitStrassenabschnittLaengeSmallerConfirmation {
            get {
                return ResourceManager.GetString("SplitStrassenabschnittLaengeSmallerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Abschnitte werden neu eingefügt / aktualisiert. Bitte prüfen sie die 2 Tabellen und bestätigen Sie den Import am Ende der 2 Tabellen..
        /// </summary>
        internal static string StrassenabschnittImportCommitInformation {
            get {
                return ResourceManager.GetString("StrassenabschnittImportCommitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind &quot;Strassenname&quot; + &quot;Bezeichnung von&quot; + &quot;Bezeichnung bis&quot; gleich wird der Strassenabschnitt aktualisiert.  Sind &quot;Strassenname&quot; + &quot;Bezeichnung von&quot; + &quot;Bezeichnung bis&quot; ungleich oder noch nicht vorhanden wird ein neuer Strassenabschnitt gebildet..
        /// </summary>
        internal static string StrassenabschnittImportInformation {
            get {
                return ResourceManager.GetString("StrassenabschnittImportInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Strassenabschnitt ist einer Inspektionsroute zugeordnet. Strassenabschnitte, die Inspektionsrouten zugeordnet wurden, können nicht gelöscht werden..
        /// </summary>
        internal static string StrassenabschnittIsInInspektionsroute {
            get {
                return ResourceManager.GetString("StrassenabschnittIsInInspektionsroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt Inspektionsrouten (im GIS-Modus), die noch nicht importiert sind. Die Routen müssen entweder importiert werden oder mit der Funktion &quot;Administration &gt; Check-Out von Inspektionsrouten rückgängig machen&quot; zurückgenommen werden. Der Jahresabschluss kann erst durchgeführt werden, wenn keine Inspektionsrouten exportiert sind..
        /// </summary>
        internal static string ThereAreLockedStrassenabschnitte {
            get {
                return ResourceManager.GetString("ThereAreLockedStrassenabschnitte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für das aktuelle Erfassungsjahr wurden eventuell noch nicht alle Daten erfasst..
        /// </summary>
        internal static string UncompletDataInCurrentErfassungsperiodNotification {
            get {
                return ResourceManager.GetString("UncompletDataInCurrentErfassungsperiodNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Für das aktuelle Erfassungsjahr wurden eventuell noch nicht alle Daten erfasst..
        /// </summary>
        internal static string UncompletDataInCurrentErfassungsperiodNotificationMap {
            get {
                return ResourceManager.GetString("UncompletDataInCurrentErfassungsperiodNotificationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler (Maximalgrösse der Datei beim Hochladen ist 10 MB).
        /// </summary>
        internal static string UploadFileLimitExceeded {
            get {
                return ResourceManager.GetString("UploadFileLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für die Lokalisierung dürfen nur RESX-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadGlobalResourceFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadGlobalResourceFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzungsdatei hochladen ....
        /// </summary>
        internal static string UploadGlobalResourceProgressText {
            get {
                return ResourceManager.GetString("UploadGlobalResourceProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für die Hilfeverwaltung dürfen nur ZIP-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadHelpSystemFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadHelpSystemFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfesystem hochladen ....
        /// </summary>
        internal static string UploadHelpSystemProgressText {
            get {
                return ResourceManager.GetString("UploadHelpSystemProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Import von Inspektionsrouten dürfen nur EMSGI-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadImportInspektionsroutenFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadImportInspektionsroutenFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandanten-Logo hochladen ....
        /// </summary>
        internal static string UploadMandantenlogoProgressText {
            get {
                return ResourceManager.GetString("UploadMandantenlogoProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für das Mandanten-Logo dürfen nur JPG-, JPEG-, BMP- oder PNG-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadMandantLogoFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadMandantLogoFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Import von Strassenabschnitten dürfen nur XLSX-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadStrassenabschnittImportFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadStrassenabschnittImportFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den Import von Zustandsabschnitten dürfen nur XLSX-Dateien hochgeladen werden!.
        /// </summary>
        internal static string UploadZustandabschnittImportFileExtensionErrorText {
            get {
                return ResourceManager.GetString("UploadZustandabschnittImportFileExtensionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Karte.
        /// </summary>
        internal static string WithMap {
            get {
                return ResourceManager.GetString("WithMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohne Karte.
        /// </summary>
        internal static string WithoutMap {
            get {
                return ResourceManager.GetString("WithoutMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die folgenden Abschnitte werden neu eingefügt / aktualisiert. Bitte prüfen sie die 2 Tabellen und bestätigen Sie den Import am Ende der 2 Tabellen..
        /// </summary>
        internal static string ZustandsabschnittImportCommitInformation {
            get {
                return ResourceManager.GetString("ZustandsabschnittImportCommitInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustandsabschnitt Import Information.
        /// </summary>
        internal static string ZustandsabschnittImportInformation {
            get {
                return ResourceManager.GetString("ZustandsabschnittImportInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie Ihre Eingaben noch nicht gespeichert haben, gehen diese bei Änderung der Art der Zustandserfassung verloren. Sind Sie sicher, dass Sie die Art der Zustandserfassung ändern möchten?.
        /// </summary>
        internal static string ZustandserfassungsmodeChangedWarning {
            get {
                return ResourceManager.GetString("ZustandserfassungsmodeChangedWarning", resourceCulture);
            }
        }
    }
}
