// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ASTRA.EMSG.IntegrationTests.Features.N_Netzverwaltung
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("N6 - Einen Strassenabschnitt in mehrere Strassenabschnitte teilen", Description="\tAls Data-Manager\r\n\twill ich einen Strassenabschnitt in mehrere Strassenabschnitt" +
        "e teilen\r\n\tdamit ich die Erfassung meins Netz hinsichtlich der tatsächlichen Bre" +
        "iten und Trottoirs vornehmen kann", SourceFile="Features\\N - Netzverwaltung\\N6.feature", SourceLine=0)]
    public partial class N6_EinenStrassenabschnittInMehrereStrassenabschnitteTeilenFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "N6.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("de-AT"), "N6 - Einen Strassenabschnitt in mehrere Strassenabschnitte teilen", "\tAls Data-Manager\r\n\twill ich einen Strassenabschnitt in mehrere Strassenabschnitt" +
                    "e teilen\r\n\tdamit ich die Erfassung meins Netz hinsichtlich der tatsächlichen Bre" +
                    "iten und Trottoirs vornehmen kann", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Mandant",
                        "Modus",
                        "Mengentyp"});
            table1.AddRow(new string[] {
                        "Mandant_1",
                        "strassennamen",
                        "Gesamtlänge"});
#line 7
testRunner.Given("folgende Einstellungen existieren:", ((string)(null)), table1, "Gegeben sei ");
#line 10
testRunner.And("ich bin Data-Manager von \'Mandant_1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table2.AddRow(new string[] {
                        "1",
                        "Hauptstrasse",
                        "0.0",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "400",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "-"});
#line 11
testRunner.And("für Mandant \'Mandant_1\' existieren folgende Netzinformationen:", ((string)(null)), table2, "Und ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Der Data-Manger kann selektieren, in wie viele Strassenabschnitte er einen besteh" +
            "enden Strassenabschnitt teilen will", new string[] {
                "Manuell"}, SourceLine=17)]
        public virtual void DerData_MangerKannSelektierenInWieVieleStrassenabschnitteErEinenBestehendenStrassenabschnittTeilenWill()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manger kann selektieren, in wie viele Strassenabschnitte er einen besteh" +
                    "enden Strassenabschnitt teilen will", new string[] {
                        "Manuell"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 19
testRunner.When("ich beim Strassenabschnitt mit der Id \'1\' auf Aufteilen klicke", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 20
testRunner.Then("kann ich 2 bis 10 Teilabschnitte auswählen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Das System generiert automatisch die Anzahl an Abschnitten, die vom Data-Manager " +
            "selektiert wurde", new string[] {
                "Manuell"}, SourceLine=24)]
        public virtual void DasSystemGeneriertAutomatischDieAnzahlAnAbschnittenDieVomData_ManagerSelektiertWurde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System generiert automatisch die Anzahl an Abschnitten, die vom Data-Manager " +
                    "selektiert wurde", new string[] {
                        "Manuell"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 26
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf 3 Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Länge"});
            table3.AddRow(new string[] {
                        "2",
                        "100"});
            table3.AddRow(new string[] {
                        "3",
                        "200"});
            table3.AddRow(new string[] {
                        "4",
                        "300"});
#line 27
testRunner.And("ich für die Teilabschnitte folgende Daten erfasse:", ((string)(null)), table3, "Und ");
#line 32
testRunner.And("ich die neuen Teilabschnitte speichere", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table4.AddRow(new string[] {
                        "2",
                        "Hauptstrasse",
                        "",
                        "",
                        "100"});
            table4.AddRow(new string[] {
                        "3",
                        "Hauptstrasse",
                        "",
                        "",
                        "200"});
            table4.AddRow(new string[] {
                        "4",
                        "Hauptstrasse",
                        "",
                        "",
                        "300"});
#line 33
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table4, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Das System übernimmt teilweise Parameter aus dem bestehenden Strassenabschnitt fü" +
            "r die gesplitteten Strassenabschnitte", new string[] {
                "Manuell"}, SourceLine=41)]
        public virtual void DasSystemUbernimmtTeilweiseParameterAusDemBestehendenStrassenabschnittFurDieGesplittetenStrassenabschnitte()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System übernimmt teilweise Parameter aus dem bestehenden Strassenabschnitt fü" +
                    "r die gesplitteten Strassenabschnitte", new string[] {
                        "Manuell"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 43
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf 2 Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Länge"});
            table5.AddRow(new string[] {
                        "2",
                        "200"});
            table5.AddRow(new string[] {
                        "3",
                        "200"});
#line 44
testRunner.And("ich für die Teilabschnitte folgende Daten erfasse:", ((string)(null)), table5, "Und ");
#line 48
testRunner.And("ich die neuen Teilabschnitte speichere", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table6.AddRow(new string[] {
                        "2",
                        "Hauptstrasse",
                        "",
                        "",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "NochNichtErfasst",
                        "",
                        "",
                        "Korporation",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "3",
                        "Hauptstrasse",
                        "",
                        "",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "NochNichtErfasst",
                        "",
                        "",
                        "Korporation",
                        "",
                        ""});
#line 49
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table6, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Der Data-Manger kann alle Attribute der neuen Strassenabschnitte bearbeiten", new string[] {
                "Automatisch"}, SourceLine=56)]
        public virtual void DerData_MangerKannAlleAttributeDerNeuenStrassenabschnitteBearbeiten()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manger kann alle Attribute der neuen Strassenabschnitte bearbeiten", new string[] {
                        "Automatisch"});
#line 57
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 58
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'3\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "1"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "0",
                        "1,1",
                        "Korporation",
                        "Glarus-Mitte",
                        "2"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "Rechts",
                        "1,2",
                        "0",
                        "Korporation",
                        "Glarus-Süd",
                        "3"});
#line 59
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table7, "Und ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "1"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "0",
                        "1,1",
                        "Korporation",
                        "Glarus-Mitte",
                        "2"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "Rechts",
                        "1,2",
                        "0",
                        "Korporation",
                        "Glarus-Süd",
                        "3"});
#line 64
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table8, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Das System löscht beim Speichern der neuen Abschnitte den ursprünglichen Strassen" +
            "abschnitt, der vom Data-Reader gesplittet wurde", new string[] {
                "Automatisch"}, SourceLine=72)]
        public virtual void DasSystemLoschtBeimSpeichernDerNeuenAbschnitteDenUrsprunglichenStrassenabschnittDerVomData_ReaderGesplittetWurde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht beim Speichern der neuen Abschnitte den ursprünglichen Strassen" +
                    "abschnitt, der vom Data-Reader gesplittet wurde", new string[] {
                        "Automatisch"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 74
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'2\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table9.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.2",
                        "200"});
            table9.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "200"});
#line 75
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table9, "Und ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table10.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.2",
                        "200"});
            table10.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "200"});
#line 79
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table10, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Das System löscht zu den Strassenabschnitten gehörende Zustände und Massnahmen", new string[] {
                "Automatisch"}, SourceLine=86)]
        public virtual void DasSystemLoschtZuDenStrassenabschnittenGehorendeZustandeUndMassnahmen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht zu den Strassenabschnitten gehörende Zustände und Massnahmen", new string[] {
                        "Automatisch"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenabschnitt",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Zustandsindex"});
            table11.AddRow(new string[] {
                        "1",
                        "0.0",
                        "0.4",
                        "1"});
#line 88
testRunner.Given("für Mandant \'Mandant_1\' existieren folgende Zustände und Massnahmen:", ((string)(null)), table11, "Gegeben sei ");
#line 91
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'2\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table12.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "-",
                        "-",
                        "Korporation",
                        "Glarus-Nord",
                        "-"});
            table12.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "1,1",
                        "-",
                        "Korporation",
                        "Glarus-Mitte",
                        "-"});
#line 92
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table12, "Und ");
#line 96
testRunner.Then("sind für den Strassenabschnitt mit der Id \'1\' keine Zustände und Massnahmen im Sy" +
                    "stem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Das System löscht erst nach Warnung und Bestätigung durch den Data-Manager", new string[] {
                "Manuell"}, SourceLine=100)]
        public virtual void DasSystemLoschtErstNachWarnungUndBestatigungDurchDenData_Manager()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht erst nach Warnung und Bestätigung durch den Data-Manager", new string[] {
                        "Manuell"});
#line 101
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Der Data-Manager kann in der Karte einen Strassenabschnitt durch Aufruf einer ent" +
            "sprechenden Funktion und Klick auf den Strassenabschnitt auf einen Strassenabsch" +
            "nitt teilen", new string[] {
                "Manuell"}, SourceLine=105)]
        public virtual void DerData_ManagerKannInDerKarteEinenStrassenabschnittDurchAufrufEinerEntsprechendenFunktionUndKlickAufDenStrassenabschnittAufEinenStrassenabschnittTeilen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manager kann in der Karte einen Strassenabschnitt durch Aufruf einer ent" +
                    "sprechenden Funktion und Klick auf den Strassenabschnitt auf einen Strassenabsch" +
                    "nitt teilen", new string[] {
                        "Manuell"});
#line 106
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Entspricht die ursprüngliche Länge des Strassenabschnitts nicht der Summe der Län" +
            "gen der neuen Strassenabschnitte, wird vom System eine Warnmeldung ausgegeben", new string[] {
                "Manuell"}, SourceLine=110)]
        public virtual void EntsprichtDieUrsprunglicheLangeDesStrassenabschnittsNichtDerSummeDerLangenDerNeuenStrassenabschnitteWirdVomSystemEineWarnmeldungAusgegeben()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entspricht die ursprüngliche Länge des Strassenabschnitts nicht der Summe der Län" +
                    "gen der neuen Strassenabschnitte, wird vom System eine Warnmeldung ausgegeben", new string[] {
                        "Manuell"});
#line 111
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("N6 - Einen Strassenabschnitt in mehrere Strassenabschnitte teilen")]
    public partial class N6_EinenStrassenabschnittInMehrereStrassenabschnitteTeilenFeature_NUnit
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "N6.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("de-AT"), "N6 - Einen Strassenabschnitt in mehrere Strassenabschnitte teilen", "\tAls Data-Manager\r\n\twill ich einen Strassenabschnitt in mehrere Strassenabschnitt" +
                    "e teilen\r\n\tdamit ich die Erfassung meins Netz hinsichtlich der tatsächlichen Bre" +
                    "iten und Trottoirs vornehmen kann", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Mandant",
                        "Modus",
                        "Mengentyp"});
            table1.AddRow(new string[] {
                        "Mandant_1",
                        "strassennamen",
                        "Gesamtlänge"});
#line 7
testRunner.Given("folgende Einstellungen existieren:", ((string)(null)), table1, "Gegeben sei ");
#line 10
testRunner.And("ich bin Data-Manager von \'Mandant_1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table2.AddRow(new string[] {
                        "1",
                        "Hauptstrasse",
                        "0.0",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "400",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "-"});
#line 11
testRunner.And("für Mandant \'Mandant_1\' existieren folgende Netzinformationen:", ((string)(null)), table2, "Und ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Der Data-Manger kann selektieren, in wie viele Strassenabschnitte er einen besteh" +
            "enden Strassenabschnitt teilen will")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void DerData_MangerKannSelektierenInWieVieleStrassenabschnitteErEinenBestehendenStrassenabschnittTeilenWill()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manger kann selektieren, in wie viele Strassenabschnitte er einen besteh" +
                    "enden Strassenabschnitt teilen will", new string[] {
                        "Manuell"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 19
testRunner.When("ich beim Strassenabschnitt mit der Id \'1\' auf Aufteilen klicke", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line 20
testRunner.Then("kann ich 2 bis 10 Teilabschnitte auswählen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Das System generiert automatisch die Anzahl an Abschnitten, die vom Data-Manager " +
            "selektiert wurde")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void DasSystemGeneriertAutomatischDieAnzahlAnAbschnittenDieVomData_ManagerSelektiertWurde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System generiert automatisch die Anzahl an Abschnitten, die vom Data-Manager " +
                    "selektiert wurde", new string[] {
                        "Manuell"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 26
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf 3 Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Länge"});
            table3.AddRow(new string[] {
                        "2",
                        "100"});
            table3.AddRow(new string[] {
                        "3",
                        "200"});
            table3.AddRow(new string[] {
                        "4",
                        "300"});
#line 27
testRunner.And("ich für die Teilabschnitte folgende Daten erfasse:", ((string)(null)), table3, "Und ");
#line 32
testRunner.And("ich die neuen Teilabschnitte speichere", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table4.AddRow(new string[] {
                        "2",
                        "Hauptstrasse",
                        "",
                        "",
                        "100"});
            table4.AddRow(new string[] {
                        "3",
                        "Hauptstrasse",
                        "",
                        "",
                        "200"});
            table4.AddRow(new string[] {
                        "4",
                        "Hauptstrasse",
                        "",
                        "",
                        "300"});
#line 33
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table4, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Das System übernimmt teilweise Parameter aus dem bestehenden Strassenabschnitt fü" +
            "r die gesplitteten Strassenabschnitte")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void DasSystemUbernimmtTeilweiseParameterAusDemBestehendenStrassenabschnittFurDieGesplittetenStrassenabschnitte()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System übernimmt teilweise Parameter aus dem bestehenden Strassenabschnitt fü" +
                    "r die gesplitteten Strassenabschnitte", new string[] {
                        "Manuell"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 43
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf 2 Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Länge"});
            table5.AddRow(new string[] {
                        "2",
                        "200"});
            table5.AddRow(new string[] {
                        "3",
                        "200"});
#line 44
testRunner.And("ich für die Teilabschnitte folgende Daten erfasse:", ((string)(null)), table5, "Und ");
#line 48
testRunner.And("ich die neuen Teilabschnitte speichere", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Und ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table6.AddRow(new string[] {
                        "2",
                        "Hauptstrasse",
                        "",
                        "",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "NochNichtErfasst",
                        "",
                        "",
                        "Korporation",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "3",
                        "Hauptstrasse",
                        "",
                        "",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "NochNichtErfasst",
                        "",
                        "",
                        "Korporation",
                        "",
                        ""});
#line 49
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table6, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Der Data-Manger kann alle Attribute der neuen Strassenabschnitte bearbeiten")]
        [NUnit.Framework.CategoryAttribute("Automatisch")]
        public virtual void DerData_MangerKannAlleAttributeDerNeuenStrassenabschnitteBearbeiten()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manger kann alle Attribute der neuen Strassenabschnitte bearbeiten", new string[] {
                        "Automatisch"});
#line 57
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 58
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'3\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "1"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "0",
                        "1,1",
                        "Korporation",
                        "Glarus-Mitte",
                        "2"});
            table7.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "Rechts",
                        "1,2",
                        "0",
                        "Korporation",
                        "Glarus-Süd",
                        "3"});
#line 59
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table7, "Und ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "0",
                        "0",
                        "Korporation",
                        "Glarus-Nord",
                        "1"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "0",
                        "1,1",
                        "Korporation",
                        "Glarus-Mitte",
                        "2"});
            table8.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "200",
                        "Rechts",
                        "1,2",
                        "0",
                        "Korporation",
                        "Glarus-Süd",
                        "3"});
#line 64
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table8, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Das System löscht beim Speichern der neuen Abschnitte den ursprünglichen Strassen" +
            "abschnitt, der vom Data-Reader gesplittet wurde")]
        [NUnit.Framework.CategoryAttribute("Automatisch")]
        public virtual void DasSystemLoschtBeimSpeichernDerNeuenAbschnitteDenUrsprunglichenStrassenabschnittDerVomData_ReaderGesplittetWurde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht beim Speichern der neuen Abschnitte den ursprünglichen Strassen" +
                    "abschnitt, der vom Data-Reader gesplittet wurde", new string[] {
                        "Automatisch"});
#line 73
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 74
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'2\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table9.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.2",
                        "200"});
            table9.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "200"});
#line 75
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table9, "Und ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Länge"});
            table10.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.2",
                        "200"});
            table10.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.2",
                        "0.4",
                        "200"});
#line 79
testRunner.Then("sind folgende Netzinformationen im System:", ((string)(null)), table10, "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Das System löscht zu den Strassenabschnitten gehörende Zustände und Massnahmen")]
        [NUnit.Framework.CategoryAttribute("Automatisch")]
        public virtual void DasSystemLoschtZuDenStrassenabschnittenGehorendeZustandeUndMassnahmen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht zu den Strassenabschnitten gehörende Zustände und Massnahmen", new string[] {
                        "Automatisch"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenabschnitt",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Zustandsindex"});
            table11.AddRow(new string[] {
                        "1",
                        "0.0",
                        "0.4",
                        "1"});
#line 88
testRunner.Given("für Mandant \'Mandant_1\' existieren folgende Zustände und Massnahmen:", ((string)(null)), table11, "Gegeben sei ");
#line 91
testRunner.When("ich den Strassenabschnitt mit der Id \'1\' auf \'2\' Teilabschnitte aufteile", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Wenn ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Strassenname",
                        "BezeichnungVon",
                        "BezeichnungBis",
                        "Belastungskategorie",
                        "Belag",
                        "BreiteFahrbahn",
                        "Länge",
                        "Trottoir",
                        "BreiteTrottoirLinks",
                        "BreiteTrottoirRechts",
                        "Strasseneigentümer",
                        "Ortsbezeichnung",
                        "Abschnittsnummer"});
            table12.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.0",
                        "0.1",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "KeinTrottoir",
                        "-",
                        "-",
                        "Korporation",
                        "Glarus-Nord",
                        "-"});
            table12.AddRow(new string[] {
                        "Hauptstrasse",
                        "0.1",
                        "0.2",
                        "IB",
                        "Asphalt",
                        "12,87",
                        "100",
                        "Links",
                        "1,1",
                        "-",
                        "Korporation",
                        "Glarus-Mitte",
                        "-"});
#line 92
    testRunner.And("ich für die Teilabschnitte folgende Daten eingebe:", ((string)(null)), table12, "Und ");
#line 96
testRunner.Then("sind für den Strassenabschnitt mit der Id \'1\' keine Zustände und Massnahmen im Sy" +
                    "stem", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dann ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Das System löscht erst nach Warnung und Bestätigung durch den Data-Manager")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void DasSystemLoschtErstNachWarnungUndBestatigungDurchDenData_Manager()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Das System löscht erst nach Warnung und Bestätigung durch den Data-Manager", new string[] {
                        "Manuell"});
#line 101
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Der Data-Manager kann in der Karte einen Strassenabschnitt durch Aufruf einer ent" +
            "sprechenden Funktion und Klick auf den Strassenabschnitt auf einen Strassenabsch" +
            "nitt teilen")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void DerData_ManagerKannInDerKarteEinenStrassenabschnittDurchAufrufEinerEntsprechendenFunktionUndKlickAufDenStrassenabschnittAufEinenStrassenabschnittTeilen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Der Data-Manager kann in der Karte einen Strassenabschnitt durch Aufruf einer ent" +
                    "sprechenden Funktion und Klick auf den Strassenabschnitt auf einen Strassenabsch" +
                    "nitt teilen", new string[] {
                        "Manuell"});
#line 106
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Entspricht die ursprüngliche Länge des Strassenabschnitts nicht der Summe der Län" +
            "gen der neuen Strassenabschnitte, wird vom System eine Warnmeldung ausgegeben")]
        [NUnit.Framework.CategoryAttribute("Manuell")]
        public virtual void EntsprichtDieUrsprunglicheLangeDesStrassenabschnittsNichtDerSummeDerLangenDerNeuenStrassenabschnitteWirdVomSystemEineWarnmeldungAusgegeben()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Entspricht die ursprüngliche Länge des Strassenabschnitts nicht der Summe der Län" +
                    "gen der neuen Strassenabschnitte, wird vom System eine Warnmeldung ausgegeben", new string[] {
                        "Manuell"});
#line 111
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
