-- ===================================================
-- Description: SQL Script for creating a new Mandant
-- Author:	    Balazs Epresi
-- Create date: 14.08.2016
-- ===================================================
-- Parameters: Insert needed Parameters below, right after the BEGIN - Statement.
-- MandantName: the Mandant's name
-- OwnerId: that Mandant's Owner's ID (e.g.: 1001)
-- Creationdate: Date of creation (default is the current time)
-- ===================================================

DECLARE
    @MANDANTNAME VARCHAR(255),
    @OWNERID VARCHAR(4),
    @CREATIONDATE datetime,
    @MANDANTID uniqueidentifier,
    @EPRID uniqueidentifier,
    @NSUID uniqueidentifier;

BEGIN
    SET @MANDANTNAME = 'Mandant 01';
    SET @OWNERID = '1001';
    SET @CREATIONDATE = GETDATE();
    SET @MANDANTID = NEWID();
    SET @EPRID = NEWID();
    SET @NSUID = NEWID();

	INSERT INTO ADD_MANDANT_MSG (MAN_ID, MAN_CREATEDAT_VL, MAN_UPDATEDAT_VL, MAN_MANDANTNAME_VL, MAN_MANDANTBEZE_VL, MAN_OWNERID_VL) 
	VALUES (@MANDANTID,@CREATIONDATE,@CREATIONDATE,@OWNERID, @MANDANTNAME, @OWNERID)

	INSERT INTO ADD_ERFPERIODE_MSG (EPR_ID, EPR_CREATEDAT_VL, EPR_UPDATEDAT_VL, EPR_NAME_VL, EPR_NETZMODUS_VL, EPR_ISTABGESCHL_VL,EPR_ERFJAHR_DT, EPR_EPR_MAN_NOR_ID) 
	VALUES (@EPRID, @CREATIONDATE, @CREATIONDATE, @OWNERID + ' InitialErfASsungsPeriod', 0, 0, @CREATIONDATE, @MANDANTID);

	INSERT INTO ADD_NETZSUM_MSG (NSU_ID, NSU_CREATEDAT_VL, NSU_UPDATEDAT_VL, NSU_NSU_MAN_NOR_ID, NSU_NSU_EPR_NOR_ID) 
	VALUES (@NSUID, @CREATIONDATE, @CREATIONDATE, @MANDANTID, @EPRID);

	INSERT INTO ADD_NETZSUMDET_MSG (NSD_ID, NSD_CREATEDAT_VL, NSD_UPDATEDAT_VL, NSD_FBLAENGE_NR, NSD_FBFLAECHE_VL, NSD_NSD_BLK_NOR_ID, NSD_NSD_NSU_NOR_ID) 
	SELECT 
		NEWID() AS NSD_ID,
		@CREATIONDATE AS NSD_CREATEDAT_VL,
		@CREATIONDATE AS NSD_UPDATEDAT_VL,
		0 AS NSD_FBLAENGE_NR,
		0 AS NSD_FBFLAECHE_VL,
		BLK_ID AS NSD_NSD_BLK_NOR_ID,
		@NSUID AS NSD_NSD_NSU_NOR_ID
	FROM VAT_BELKAT_MSG;

	INSERT INTO VAT_WBBKAT_MSG (WBK_ID,WBK_CREATEDAT_VL,WBK_UPDATEDAT_VL,WBK_FLAEGESFB_NR,WBK_FLAECHEFB_NR,WBK_FLAECHETR_NR,WBK_ALTERUNGI_NR,WBK_ALTERUNGII_NR,WBK_ISCUSTOMIZE_VL,WBK_WBK_BLK_NOR_ID,WBK_WBK_MAN_NOR_ID,WBK_WBK_EPR_NOR_ID) 
	SELECT
		NEWID() AS WBK_ID,
		@CREATIONDATE AS WBK_CREATEDAT_VL,
		@CREATIONDATE AS WBK_UPDATEDAT_VL,
		GWK_FLAECHEFB_NR AS WBK_FLAEGESFB_NR,
		GWK_FLAECHEFB_NR AS WBK_FLAECHEFB_NR,
		GWK_FLAECHETR_NR AS WBK_FLAECHETR_NR,
		GWK_ALTERUNGI_NR AS WBK_ALTERUNGI_NR,
		GWK_ALTERUNGII_NR AS WBK_ALTERUNGII_NR,
		0 AS WBK_ISCUSTOMIZE_VL,
		GWK_GWK_BLK_NOR_ID AS WBK_WBK_BLK_NOR_ID,
		@MANDANTID AS WBK_WBK_MAN_NOR_ID,
		@EPRID AS WBK_WBK_EPR_NOR_ID
	FROM VAT_GWBBKAT_MSG;

	INSERT INTO VAT_MASSVORSCH_MSG (MVK_ID,MVK_CREATEDAT_VL,MVK_UPDATEDAT_VL,MVK_DEFKOSTEN_NR,MVK_ISCUSTOMIZE_VL,MVK_MVK_BLK_NOR_ID,MVK_MVK_MTK_NOR_ID,MVK_MVK_MAN_NOR_ID,MVK_MVK_EPR_NOR_ID) 
	SELECT
		NEWID() AS WBK_ID,
		@CREATIONDATE AS MVK_CREATEDAT_VL,
		@CREATIONDATE AS MVK_UPDATEDAT_VL,		
		GMK_DEFKOSTEN_NR AS MVK_DEFKOSTEN_NR,
		0 AS RMK_ISCUSTOMIZE_VL,
		GMK_GMK_BLK_NOR_ID AS MVK_MVK_BLK_NOR_ID,
		GMK_GMK_MTK_NOR_ID AS MVK_MVK_MTK_NOR_ID,
		@MANDANTID AS MVK_MVK_MAN_NOR_ID,
		@EPRID AS MVK_MVK_EPR_NOR_ID
	FROM VAT_GMASSVOR_MSG;

	INSERT INTO ADD_MANDANTDET_MSG (MAD_ID,MAD_CREATEDAT_VL,MAD_UPDATEDAT_VL,MAD_NETZLAENGE_NR,MAD_ISCOMPLETED_VL,MAD_MAD_MAN_NOR_ID,MAD_MAD_EPR_NOR_ID) 
	VALUES (NEWID(), @CREATIONDATE, @CREATIONDATE, 0, 0, @MANDANTID, @EPRID);

END

-------------------------------------------------------------------------------------
